# coding=UTF-8
# These glyphs, and the mapping of file extensions to glyphs
# has been copied from the vimscript code that is present in
# https://github.com/ryanoasis/vim-devicons
import re
import os
from subprocess import run

# all those glyphs will show as weird squares if you don't have the correct patched font
# My advice is to use NerdFonts which can be found here:
# https://github.com/ryanoasis/nerd-fonts
file_node_extensions = {
    '7z': '',
    'a': '',
    'ai': '',
    'apk': '',
    'asm': '',
    'asp': '',
    'aup': '',
    'avi': '',
    'awk': '',
    'bash': '',
    'bat': '',
    'bmp': '',
    'bz2': '',
    'c': '',
    'c++': '',
    'cab': '',
    'cbr': '',
    'cbz': '',
    'cc': '',
    'class': '',
    'clj': '',
    'cljc': '',
    'cljs': '',
    'cmake': '',
    'coffee': '',
    'conf': '',
    'cp': '',
    'cpio': '',
    'cpp': '',
    'cs': '',
    'csh': '',
    'css': '',
    'cue': '',
    'cvs': '',
    'cxx': '',
    'd': '',
    'dart': '',
    'db': '',
    'deb': '',
    'diff': '',
    'dll': '',
    'doc': '',
    'docx': '',
    'dump': '',
    'edn': '',
    'eex': '',
    'efi': '',
    'ejs': '',
    'elf': '',
    'elm': '',
    'epub': '',
    'erl': '',
    'ex': '',
    'exe': '',
    'exs': '',
    'f#': '',
    'fifo': '|',
    'fish': '',
    'flac': '',
    'flv': '',
    'fs': '',
    'fsi': '',
    'fsscript': '',
    'fsx': '',
    'gem': '',
    'gemspec': '',
    'gif': '',
    'go': '',
    'gz': '',
    'gzip': '',
    'h': '',
    'haml': '',
    'hbs': '',
    'hh': '',
    'hpp': '',
    'hrl': '',
    'hs': '',
    'htaccess': '',
    'htm': '',
    'html': '',
    'htpasswd': '',
    'hxx': '',
    'ico': '',
    'img': '',
    'ini': '',
    'iso': '',
    'jar': '',
    'java': '',
    'jl': '',
    'jpeg': '',
    'jpg': '',
    'js': '',
    'json': '',
    'jsx': '',
    'key': '',
    'ksh': '',
    'leex': '',
    'less': '',
    'lha': '',
    'lhs': '',
    'log': '',
    'lua': '',
    'lzh': '',
    'lzma': '',
    'm4a': '',
    'm4v': '',
    'markdown': '',
    'md': '',
    'mdx': '',
    'mjs': '',
    'mkv': '',
    'ml': 'λ',
    'mli': 'λ',
    'mov': '',
    'mp3': '',
    'mp4': '',
    'mpeg': '',
    'mpg': '',
    'msi': '',
    'mustache': '',
    'nix': '',
    'o': '',
    'ogg': '',
    'pdf': '',
    'php': '',
    'pl': '',
    'pm': '',
    'png': '',
    'pp': '',
    'ppt': '',
    'pptx': '',
    'ps1': '',
    'psb': '',
    'psd': '',
    'pub': '',
    'py': '',
    'pyc': '',
    'pyd': '',
    'pyo': '',
    'r': 'ﳒ',
    'rake': '',
    'rar': '',
    'rb': '',
    'rc': '',
    'rlib': '',
    'rmd': '',
    'rom': '',
    'rpm': '',
    'rproj': '',
    'rs': '',
    'rss': '',
    'rtf': '',
    's': '',
    'sass': '',
    'scala': '',
    'scss': '',
    'sh': '',
    'slim': '',
    'sln': '',
    'so': '',
    'sql': '',
    'styl': '',
    'suo': '',
    'swift': '',
    't': '',
    'tar': '',
    'tex': 'ﭨ',
    'tgz': '',
    'toml': '',
    'ts': '',
    'tsx': '',
    'twig': '',
    'txt': '󰊄',
    'vim': '',
    'vimrc': '',
    'vue': '﵂',
    'wav': '',
    'webm': '',
    'webmanifest': '',
    'webp': '',
    'xbps': '',
    'xcplayground': '',
    'xhtml': '',
    'xls': '',
    'xlsx': '',
    'xml': '',
    'xul': '',
    'xz': '',
    'yaml': '',
    'yml': '',
    'zip': '',
    'zsh': '',
}

# user = run(['whoami'], capture_output=True, text=True)
# downloads = run(['fish', '-c', 'xdg-user-dir DOWNLOAD | path basename'],
#                 capture_output=True, text=True)
# documents = run(['fish', '-c', 'xdg-user-dir DOCUMENTS | path basename'],
#                 capture_output=True, text=True)
# photos = run(['fish', '-c', 'xdg-user-dir PICTURES | path basename'],
#              capture_output=True, text=True)
# videos = run(['fish', '-c', 'xdg-user-dir VIDEOS | path basename'],
#              capture_output=True, text=True)
# templates = run(['fish', '-c', 'xdg-user-dir TEMPLATES | path basename'],
#                 capture_output=True, text=True)
# public = run(['fish', '-c', 'xdg-user-dir PUBLICSHARE | path basename'],
#              capture_output=True, text=True)
# music = run(['fish', '-c', 'xdg-user-dir MUSIC | path basename'],
#             capture_output=True, text=True)

dir_node_exact_matches = {
    # user.stdout.strip(): '󰋜',
    # downloads.stdout.strip(): '',
    # documents.stdout.strip(): '',
    # photos.stdout.strip(): '',
    # videos.stdout.strip(): '',
    # public.stdout.strip(): '',
    # templates.stdout.strip(): '',
    # music.stdout.strip(): '',
    'documents'     : '',
    'downloads'     : '',
    'videos'        : '',
    'muhammadsodiq' : '󰋜',
    'photos'        : '',
}

file_node_exact_matches = {}

def devicon(file):
    if file.is_directory:
        return dir_node_exact_matches.get(file.relative_path, '')
    return file_node_exact_matches.get(os.path.basename(file.relative_path), file_node_extensions.get(file.extension, '󰈚'))
