#!/bin/sh

option=$(
    printf "   Lock\n   Shutdown\n   Reboot" | \
        rofi -dmenu -i -replace \
        -theme powermenu \
        -p 'Power Menu'
)

case "$option" in
    "   Lock") /bin/hyprlock ;;
    "   Shutdown") sudo /sbin/poweroff ;;
    "   Reboot") sudo /sbin/reboot ;;
    *) exit 0 ;;
esac

