[cursor]
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[selection]
save_to_clipboard = true

[window]
opacity = 0.5

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
  { key = "k", mods = "Alt", action = "ScrollLineUp" },
  { key = "j", mods = "Alt", action = "ScrollLineDown" },
]

[colors]
primary = { background = "#282828" }

[colors.normal]
black = "#4D5264"
red = "#E15050"
green = "#AEBA40"
yellow = "#E1B563"
blue = "#46B3C9"
magenta = "#988BCC"
cyan = "#85D3E3"
white = "#DFDED8"

[colors.bright]
black = "#5C6075"
red = "#fb4934"
green = "#AAC755"
yellow = "#fabd2f"
blue = "#5DBBCD"
magenta = "#CA9EE6"
cyan = "#9AE6E5"
white = "#DEDDD7"


